#!/bin/bash
#
# Install dotfiles.

echo "[+] Installing dotfiles" 
dir="$(cd "$(dirname "$0")" && pwd)"
files="$(ls -a "$dir")"
ignore=".git . .. README.md install"

echo "[+] Ignoring files"
for file in $ignore; do
  printf "  ${file}"
  files="${files/"$file"}"
done

echo "[+] Linking dotfiles"
for file in $files; do
  src="${dir}/${file}"
  link="${HOME}/.${file}"
  echo "  ln -snf ${src} ${link}"
  ln -snf "$src" "$link"
done

echo "[+] All done!"
